name: Commit pipeline

on: 
  push:
jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Updrade pip
      run: >-
        python -m pip install -U pip
    - name: Install requirements
      run: >-
        python -m pip install -r requirements/dev.txt --user
    - name: Run pytest
      run: >-
        python -m pytest test/
    - name: Run pylint
      run: >-
        python -m pylint pyppy/
    - name: Run doctests
      run: >-
        python -m pytest --doctest-modules pyppy/
