name: Commit pipeline

on: 
  push:
jobs:
  run-tests:
    name: Run pytest tests
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install requirements
      run: >-
        python -m
        pip install -r
        dev_requirements.txt
        --user
    - name: Run pytest
      run: >-
        python -m pytest test/
    - name: Run pylint
        run: >-
          python -m pylint pyppy/
