name: Publish to pypi

on: 
  release:
    types: [created]
  workflow_dispatch:
jobs:
  run-tests:
    name: Run tests with pytest
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pytest
      run: >-
        python -m
        pip install
        pytest
        --user
    - name: Run pytest
      run: >-
        python -m pytest test/
  build-n-publish:
    name: Build and publish python distribution to pypi
    needs: [run-tests]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Install pytest
      run: >-
        python -m
        pip install
        pytest
        --user
    - name: Run pytest
      run: >-
        python -m pytest test/
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish distribution to pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
